kube-aws: do not kms encrypt certs
Certificate PEM files are not sensitive - Additionally they may be
significantly larger than 4k compressed and base64'd if intermediate CAs
are included (bundling).

Such setups may cause kms errors such as

```
Error: failed to compress TLS assets: ValidationException: 1 validation
error detected: Value at 'plaintext' failed to satisfy constraint:
Member must have length less than or equal to 4096
```

Split out the encryption and compression functions, and don't use
encryption on certs.

I've left encoding on the interpolated certs as is for consistency, and
to prevent sensitivity to input format in the rendered yaml files